# Generated by Django 4.2.5 on 2023-11-06 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0004_alter_user_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealEstate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=255, null=True)),
                ("city", models.CharField(max_length=255, null=True)),
                ("street", models.CharField(max_length=255, null=True)),
                ("house_number", models.CharField(max_length=255, null=True)),
                ("apartment_number", models.CharField(max_length=255, null=True)),
                ("latitude", models.CharField(max_length=255, null=True)),
                ("longitude", models.CharField(max_length=255, null=True)),
                ("floor", models.CharField(max_length=255, null=True)),
                ("number_of_floors", models.CharField(max_length=255, null=True)),
                ("number_of_rooms", models.CharField(max_length=255, null=True)),
                ("square", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User_Real_estate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_real_estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.realestate",
                    ),
                ),
            ],
        ),
    ]
