# Generated by Django 4.2.5 on 2023-11-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0005_realestate_user_real_estate"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestate",
            name="heading",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
