# Generated by Django 4.2.5 on 2023-11-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0006_realestate_heading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestate",
            name="heading",
            field=models.CharField(default=1, max_length=255),
        ),
    ]
