# Generated by Django 4.2.7 on 2023-11-12 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0011_deal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deal",
            old_name="demand_id",
            new_name="demand",
        ),
        migrations.RenameField(
            model_name="deal",
            old_name="offer_id",
            new_name="offer",
        ),
    ]
