# Generated by Django 4.2.7 on 2023-11-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0012_rename_demand_id_deal_demand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="delete",
            field=models.BooleanField(default=True),
        ),
    ]
