# Generated by Django 4.2.7 on 2023-11-13 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0014_rename_delete_user_delete_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestate",
            name="latitude",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="longitude",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
    ]
