# Generated by Django 4.2.5 on 2023-11-15 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_realestate_latx_alter_realestate_lngy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='realestate',
            name='latX',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='lngY',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
