# Generated by Django 4.2.1 on 2023-12-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
